.TH HSH 1 "April 21, 2026"
.SH NAME
hsh \- a simple command interpreter

.SH SYNOPSIS
.B ./hsh

.SH DESCRIPTION
.B hsh
is a simplified implementation of a UNIX command interpreter. It allows the execution of system commands, and basic stream manipulation.

The shell displays a prompt and waits for the user to input a command. Then, it searches for the executable in the paths defined by the PATH variable or via the provided relative/absolute path.

The prompt used in this shell is "<3"

.SH FEATURES
.TP
.B Built-in commands
Handles native commands such as
.B 'exit'
, and
.B 'env'.
.TP
.B Reading
Reads the output of the user.
.TP
.B Parsing
Parses the output of the user and send the command to the execution part.
.TP
.B Execution
Launches programs using fork and execve.
.TP
.B Loop
Waits for another input to be typed.
.TP

.SH EXAMPLES
.PP
.I Launch the shell interactively:
.RS
.nf
<3 ./hsh
.fi
.RE

.PP
.I Execute a simple command:
.RS
.nf
<3 /bin/ls
.fi
.RE

.PP
.I Execute a command found in the PATH, with or without arguments:
.RS
.nf
<3 ls -l
.fi
.RE

.SH EXIT STATUS
.TP
Errors that are detected by the shell, such as a syntax error, will cause the shell to exit with a non-zero exit status.  

If the shell is not an interactive shell, the execution of  the shell file will be aborted.  

Otherwise the shell will return the exit status of the last command executed, or if the exit builtin is used with a numeric argument, it will return the argument.

.SH AUTHOR
Guillaume VAUDET & Maxime BERNIER

.SH SEE ALSO
getline(3), sh(1), bash(1), execve(2), fork(2), wait(2), strtok(3)